######################################################################
#
# File name : tb_compile.do
# Created on: Fri Dec 17 11:01:57 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech64_2019.2\\win64\\vlib modelsim_lib/work
C:\\modeltech64_2019.2\\win64\\vlib modelsim_lib/msim

C:\\modeltech64_2019.2\\win64\\vlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_2019.2\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_2019.2\\win64\\vcom -64 -93 -work xil_defaultlib  \
"../../../../nvdla_bp.ip_user_files/bd/design_1/ip/design_1_microblaze_0_0/sim/design_1_microblaze_0_0.vhd" \
"../../../../nvdla_bp.ip_user_files/bd/design_1/ip/design_1_dlmb_v10_1/sim/design_1_dlmb_v10_1.vhd" \
"../../../../nvdla_bp.ip_user_files/bd/design_1/ip/design_1_ilmb_v10_1/sim/design_1_ilmb_v10_1.vhd" \
"../../../../nvdla_bp.ip_user_files/bd/design_1/ip/design_1_dlmb_bram_if_cntlr_1/sim/design_1_dlmb_bram_if_cntlr_1.vhd" \
"../../../../nvdla_bp.ip_user_files/bd/design_1/ip/design_1_ilmb_bram_if_cntlr_1/sim/design_1_ilmb_bram_if_cntlr_1.vhd" \

C:\\modeltech64_2019.2\\win64\\vlog -64 -incr -work xil_defaultlib "D:/VM_share/NVDLA_BP/spinal_prj/SpinalTemplateSbt-master/VerilogHDL/enumdefine.v" "+incdir+../../../../nvdla_bp.srcs/sources_1/bd/design_1/ipshared/85a3" "+incdir+../../../../nvdla_bp.srcs/sources_1/ip/ddr4_0/rtl/ip_top" "+incdir+../../../../nvdla_bp.srcs/sources_1/ip/ddr4_0/rtl/cal" "+incdir+../../../../nvdla_bp.srcs/sources_1/ip/ddr4_0/ip_1/rtl/map" \
"../../../../nvdla_bp.ip_user_files/bd/design_1/ip/design_1_lmb_bram_1/sim/design_1_lmb_bram_1.v" \

C:\\modeltech64_2019.2\\win64\\vcom -64 -93 -work xil_defaultlib  \
"../../../../nvdla_bp.ip_user_files/bd/design_1/ip/design_1_mdm_1_1/sim/design_1_mdm_1_1.vhd" \

C:\\modeltech64_2019.2\\win64\\vlog -64 -incr -work xil_defaultlib "D:/VM_share/NVDLA_BP/spinal_prj/SpinalTemplateSbt-master/VerilogHDL/enumdefine.v" "+incdir+../../../../nvdla_bp.srcs/sources_1/bd/design_1/ipshared/85a3" "+incdir+../../../../nvdla_bp.srcs/sources_1/ip/ddr4_0/rtl/ip_top" "+incdir+../../../../nvdla_bp.srcs/sources_1/ip/ddr4_0/rtl/cal" "+incdir+../../../../nvdla_bp.srcs/sources_1/ip/ddr4_0/ip_1/rtl/map" \
"../../../../nvdla_bp.ip_user_files/bd/design_1/ip/design_1_clk_wiz_1_1/design_1_clk_wiz_1_1_clk_wiz.v" \
"../../../../nvdla_bp.ip_user_files/bd/design_1/ip/design_1_clk_wiz_1_1/design_1_clk_wiz_1_1.v" \

C:\\modeltech64_2019.2\\win64\\vcom -64 -93 -work xil_defaultlib  \
"../../../../nvdla_bp.ip_user_files/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_1/sim/design_1_rst_clk_wiz_1_100M_1.vhd" \
"../../../../nvdla_bp.ip_user_files/bd/design_1/ip/design_1_axi_apb_bridge_0_0/sim/design_1_axi_apb_bridge_0_0.vhd" \

C:\\modeltech64_2019.2\\win64\\vlog -64 -incr -work xil_defaultlib "D:/VM_share/NVDLA_BP/spinal_prj/SpinalTemplateSbt-master/VerilogHDL/enumdefine.v" "+incdir+../../../../nvdla_bp.srcs/sources_1/bd/design_1/ipshared/85a3" "+incdir+../../../../nvdla_bp.srcs/sources_1/ip/ddr4_0/rtl/ip_top" "+incdir+../../../../nvdla_bp.srcs/sources_1/ip/ddr4_0/rtl/cal" "+incdir+../../../../nvdla_bp.srcs/sources_1/ip/ddr4_0/ip_1/rtl/map" \
"../../../../nvdla_bp.ip_user_files/bd/design_1/sim/design_1.v" \

C:\\modeltech64_2019.2\\win64\\vcom -64 -93 -work xil_defaultlib  \
"../../../../nvdla_bp.srcs/sources_1/ip/fp_adder_bb/sim/fp_adder_bb.vhd" \
"../../../../nvdla_bp.srcs/sources_1/ip/fp_multi_bb/sim/fp_multi_bb.vhd" \

C:\\modeltech64_2019.2\\win64\\vlog -64 -incr -work xil_defaultlib "D:/VM_share/NVDLA_BP/spinal_prj/SpinalTemplateSbt-master/VerilogHDL/enumdefine.v" "+incdir+../../../../nvdla_bp.srcs/sources_1/bd/design_1/ipshared/85a3" "+incdir+../../../../nvdla_bp.srcs/sources_1/ip/ddr4_0/rtl/ip_top" "+incdir+../../../../nvdla_bp.srcs/sources_1/ip/ddr4_0/rtl/cal" "+incdir+../../../../nvdla_bp.srcs/sources_1/ip/ddr4_0/ip_1/rtl/map" \
"../../../../../../SpinalTemplateSbt-master/VerilogHDL/bp_fpga_top.v" \
"../../../../nvdla_bp.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v" \
"../../../../../../hand_rtl/mem_sim_model.v" \
"../../../../nvdla_bp.srcs/sim_1/new/tb.v" \

# compile glbl module
C:\\modeltech64_2019.2\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

