######################################################################
#
# File name : tb_wave.do
# Created on: Fri Dec 17 10:32:59 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
