# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param simulator.modelsimInstallPath C:/modeltech64_2019.2/win64
set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xcvu440-flga2892-1-c

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.cache/wt [current_project]
set_property parent.project_path D:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet d:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.srcs/sources_1/ip/blk_ram256_1024_bb/blk_ram256_1024_bb.xci
set_property used_in_implementation false [get_files -all d:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.srcs/sources_1/ip/blk_ram256_1024_bb/blk_ram256_1024_bb_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir D:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.runs/blk_ram256_1024_bb_synth_1 -new_name blk_ram256_1024_bb -ip [get_ips blk_ram256_1024_bb]]

if { $cached_ip eq {} } {
close [open __synthesis_is_running__ w]

synth_design -top blk_ram256_1024_bb -part xcvu440-flga2892-1-c -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
# disable binary constraint mode for IPCache checkpoints
set_param constraints.enableBinaryConstraints false

catch {
 write_checkpoint -force -noxdef -rename_prefix blk_ram256_1024_bb_ blk_ram256_1024_bb.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ blk_ram256_1024_bb_stub.v
 lappend ipCachedFiles blk_ram256_1024_bb_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ blk_ram256_1024_bb_stub.vhdl
 lappend ipCachedFiles blk_ram256_1024_bb_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ blk_ram256_1024_bb_sim_netlist.v
 lappend ipCachedFiles blk_ram256_1024_bb_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ blk_ram256_1024_bb_sim_netlist.vhdl
 lappend ipCachedFiles blk_ram256_1024_bb_sim_netlist.vhdl
set TIME_taken [expr [clock seconds] - $TIME_start]

 config_ip_cache -add -dcp blk_ram256_1024_bb.dcp -move_files $ipCachedFiles -use_project_ipc  -synth_runtime $TIME_taken  -ip [get_ips blk_ram256_1024_bb]
}

rename_ref -prefix_all blk_ram256_1024_bb_

# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef blk_ram256_1024_bb.dcp
create_report "blk_ram256_1024_bb_synth_1_synth_report_utilization_0" "report_utilization -file blk_ram256_1024_bb_utilization_synth.rpt -pb blk_ram256_1024_bb_utilization_synth.pb"

if { [catch {
  file copy -force D:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.runs/blk_ram256_1024_bb_synth_1/blk_ram256_1024_bb.dcp d:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.srcs/sources_1/ip/blk_ram256_1024_bb/blk_ram256_1024_bb.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub d:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.srcs/sources_1/ip/blk_ram256_1024_bb/blk_ram256_1024_bb_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub d:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.srcs/sources_1/ip/blk_ram256_1024_bb/blk_ram256_1024_bb_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim d:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.srcs/sources_1/ip/blk_ram256_1024_bb/blk_ram256_1024_bb_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim d:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.srcs/sources_1/ip/blk_ram256_1024_bb/blk_ram256_1024_bb_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force D:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.runs/blk_ram256_1024_bb_synth_1/blk_ram256_1024_bb.dcp d:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.srcs/sources_1/ip/blk_ram256_1024_bb/blk_ram256_1024_bb.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force D:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.runs/blk_ram256_1024_bb_synth_1/blk_ram256_1024_bb_stub.v d:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.srcs/sources_1/ip/blk_ram256_1024_bb/blk_ram256_1024_bb_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force D:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.runs/blk_ram256_1024_bb_synth_1/blk_ram256_1024_bb_stub.vhdl d:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.srcs/sources_1/ip/blk_ram256_1024_bb/blk_ram256_1024_bb_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force D:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.runs/blk_ram256_1024_bb_synth_1/blk_ram256_1024_bb_sim_netlist.v d:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.srcs/sources_1/ip/blk_ram256_1024_bb/blk_ram256_1024_bb_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force D:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.runs/blk_ram256_1024_bb_synth_1/blk_ram256_1024_bb_sim_netlist.vhdl d:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.srcs/sources_1/ip/blk_ram256_1024_bb/blk_ram256_1024_bb_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir D:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.ip_user_files/ip/blk_ram256_1024_bb]} {
  catch { 
    file copy -force d:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.srcs/sources_1/ip/blk_ram256_1024_bb/blk_ram256_1024_bb_stub.v D:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.ip_user_files/ip/blk_ram256_1024_bb
  }
}

if {[file isdir D:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.ip_user_files/ip/blk_ram256_1024_bb]} {
  catch { 
    file copy -force d:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.srcs/sources_1/ip/blk_ram256_1024_bb/blk_ram256_1024_bb_stub.vhdl D:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.ip_user_files/ip/blk_ram256_1024_bb
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
