# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.srcs/sources_1/ip/blk_ram256_1024_bb/blk_ram256_1024_bb.xci
# IP: The module: 'blk_ram256_1024_bb' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.srcs/sources_1/ip/blk_ram256_1024_bb/blk_ram256_1024_bb_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_ram256_1024_bb'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.srcs/sources_1/ip/blk_ram256_1024_bb/blk_ram256_1024_bb.xci
# IP: The module: 'blk_ram256_1024_bb' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.srcs/sources_1/ip/blk_ram256_1024_bb/blk_ram256_1024_bb_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_ram256_1024_bb'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
