
`define acc_fsm_enumDefinition_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_1_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_1_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_1_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_1_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_1_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_1_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_1_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_1_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_2_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_2_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_2_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_2_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_2_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_2_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_2_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_2_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_3_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_3_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_3_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_3_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_3_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_3_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_3_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_3_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_4_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_4_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_4_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_4_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_4_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_4_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_4_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_4_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_5_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_5_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_5_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_5_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_5_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_5_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_5_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_5_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_6_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_6_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_6_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_6_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_6_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_6_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_6_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_6_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_7_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_7_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_7_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_7_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_7_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_7_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_7_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_7_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_8_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_8_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_8_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_8_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_8_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_8_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_8_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_8_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_9_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_9_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_9_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_9_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_9_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_9_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_9_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_9_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_10_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_10_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_10_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_10_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_10_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_10_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_10_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_10_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_11_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_11_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_11_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_11_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_11_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_11_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_11_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_11_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_12_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_12_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_12_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_12_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_12_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_12_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_12_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_12_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_13_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_13_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_13_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_13_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_13_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_13_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_13_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_13_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_14_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_14_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_14_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_14_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_14_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_14_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_14_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_14_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_15_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_15_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_15_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_15_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_15_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_15_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_15_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_15_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_16_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_16_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_16_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_16_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_16_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_16_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_16_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_16_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_17_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_17_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_17_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_17_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_17_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_17_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_17_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_17_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_18_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_18_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_18_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_18_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_18_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_18_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_18_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_18_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_19_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_19_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_19_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_19_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_19_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_19_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_19_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_19_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_20_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_20_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_20_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_20_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_20_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_20_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_20_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_20_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_21_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_21_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_21_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_21_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_21_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_21_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_21_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_21_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_22_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_22_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_22_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_22_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_22_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_22_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_22_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_22_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_23_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_23_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_23_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_23_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_23_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_23_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_23_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_23_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_24_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_24_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_24_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_24_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_24_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_24_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_24_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_24_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_25_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_25_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_25_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_25_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_25_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_25_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_25_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_25_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_26_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_26_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_26_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_26_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_26_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_26_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_26_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_26_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_27_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_27_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_27_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_27_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_27_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_27_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_27_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_27_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_28_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_28_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_28_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_28_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_28_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_28_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_28_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_28_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_29_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_29_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_29_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_29_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_29_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_29_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_29_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_29_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_30_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_30_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_30_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_30_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_30_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_30_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_30_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_30_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_31_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_31_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_31_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_31_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_31_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_31_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_31_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_31_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_32_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_32_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_32_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_32_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_32_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_32_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_32_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_32_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_33_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_33_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_33_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_33_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_33_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_33_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_33_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_33_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_34_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_34_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_34_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_34_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_34_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_34_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_34_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_34_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_35_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_35_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_35_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_35_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_35_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_35_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_35_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_35_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_36_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_36_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_36_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_36_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_36_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_36_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_36_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_36_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_37_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_37_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_37_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_37_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_37_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_37_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_37_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_37_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_38_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_38_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_38_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_38_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_38_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_38_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_38_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_38_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_39_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_39_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_39_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_39_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_39_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_39_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_39_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_39_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_40_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_40_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_40_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_40_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_40_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_40_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_40_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_40_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_41_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_41_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_41_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_41_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_41_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_41_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_41_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_41_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_42_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_42_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_42_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_42_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_42_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_42_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_42_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_42_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_43_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_43_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_43_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_43_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_43_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_43_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_43_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_43_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_44_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_44_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_44_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_44_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_44_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_44_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_44_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_44_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_45_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_45_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_45_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_45_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_45_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_45_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_45_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_45_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_46_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_46_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_46_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_46_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_46_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_46_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_46_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_46_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_47_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_47_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_47_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_47_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_47_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_47_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_47_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_47_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_48_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_48_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_48_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_48_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_48_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_48_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_48_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_48_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_49_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_49_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_49_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_49_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_49_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_49_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_49_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_49_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_50_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_50_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_50_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_50_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_50_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_50_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_50_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_50_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_51_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_51_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_51_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_51_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_51_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_51_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_51_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_51_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_52_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_52_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_52_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_52_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_52_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_52_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_52_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_52_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_53_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_53_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_53_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_53_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_53_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_53_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_53_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_53_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_54_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_54_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_54_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_54_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_54_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_54_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_54_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_54_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_55_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_55_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_55_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_55_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_55_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_55_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_55_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_55_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_56_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_56_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_56_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_56_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_56_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_56_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_56_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_56_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_57_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_57_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_57_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_57_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_57_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_57_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_57_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_57_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_58_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_58_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_58_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_58_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_58_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_58_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_58_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_58_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_59_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_59_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_59_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_59_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_59_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_59_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_59_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_59_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_60_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_60_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_60_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_60_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_60_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_60_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_60_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_60_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_61_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_61_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_61_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_61_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_61_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_61_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_61_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_61_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_62_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_62_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_62_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_62_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_62_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_62_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_62_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_62_binary_sequential_acc_fsm_OUT 3'b110

`define acc_fsm_enumDefinition_63_binary_sequential_type [2:0]
`define acc_fsm_enumDefinition_63_binary_sequential_acc_fsm_BOOT 3'b000
`define acc_fsm_enumDefinition_63_binary_sequential_acc_fsm_IDLE 3'b001
`define acc_fsm_enumDefinition_63_binary_sequential_acc_fsm_INIT 3'b010
`define acc_fsm_enumDefinition_63_binary_sequential_acc_fsm_INPUT 3'b011
`define acc_fsm_enumDefinition_63_binary_sequential_acc_fsm_CACU 3'b100
`define acc_fsm_enumDefinition_63_binary_sequential_acc_fsm_CHECK 3'b101
`define acc_fsm_enumDefinition_63_binary_sequential_acc_fsm_OUT 3'b110

