# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param simulator.modelsimInstallPath C:/modeltech64_2019.2/win64
create_project -in_memory -part xcvu440-flga2892-1-c

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.cache/wt [current_project]
set_property parent.project_path D:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/VM_share/NVDLA_BP/spinal_prj/SpinalTemplateSbt-master/VerilogHDL/enumdefine.v
  D:/VM_share/NVDLA_BP/spinal_prj/SpinalTemplateSbt-master/VerilogHDL/mac_acc_array.v
  D:/VM_share/NVDLA_BP/spinal_prj/SpinalTemplateSbt-master/VerilogHDL/conv_top.v
}
read_ip -quiet D:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.srcs/sources_1/ip/fp_adder_bb/fp_adder_bb.xci
set_property used_in_implementation false [get_files -all d:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.srcs/sources_1/ip/fp_adder_bb/fp_adder_bb_ooc.xdc]

read_ip -quiet D:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.srcs/sources_1/ip/fp_multi_bb/fp_multi_bb.xci
set_property used_in_implementation false [get_files -all d:/VM_share/NVDLA_BP/spinal_prj/vivado/nvdla_bp/nvdla_bp.srcs/sources_1/ip/fp_multi_bb/fp_multi_bb_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top conv_top -part xcvu440-flga2892-1-c


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef conv_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file conv_top_utilization_synth.rpt -pb conv_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
