# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/fp_adder_bb/fp_adder_bb.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fp_adder_bb || ORIG_REF_NAME==fp_adder_bb} -quiet] -quiet

# IP: ip/fp_multi_bb/fp_multi_bb.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fp_multi_bb || ORIG_REF_NAME==fp_multi_bb} -quiet] -quiet
